workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60
    environment:
      node: 20
      java: 17
    scripts:
      - npm install
      - npm run mobile:build
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
